language: php

php:
  - 5.4

env:
  - DB=mysql DB_USER=root

before_script:
  # MySQL
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'SET FOREIGN_KEY_CHECKS = 0; DROP DATABASE IF EXISTS test; DROP SCHEMA IF EXISTS second_hand_books; DROP SCHEMA IF EXISTS contest; DROP SCHEMA IF EXISTS bookstore_schemas; SET FOREIGN_KEY_CHECKS = 1;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE test; CREATE SCHEMA bookstore_schemas; CREATE SCHEMA contest; CREATE SCHEMA second_hand_books;'; fi"

  # Composer
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

  - php bin/propel test:prepare --vendor="$DB" --dsn="$DB:dbname=test" --user="$DB_USER"

script: phpunit -v /Users/jeremyFreeAgent/GitHub/Propel2/tests/Propel/Tests/Ticket520Test.php
